code --install-extension aeschli.vscode-css-formatter
code --install-extension bierner.markdown-preview-github-styles
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension donjayamanne.githistory
code --install-extension dpastoor.vscode-nm
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension formulahendry.code-runner
code --install-extension Gruntfuggly.todo-tree
code --install-extension huizhou.githd
code --install-extension kamikillerto.vscode-colorize
code --install-extension letmaik.git-tree-compare
code --install-extension mechatroner.rainbow-csv
code --install-extension michelemelluso.code-beautifier
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension naumovs.color-highlight
code --install-extension nobuhito.printcode
code --install-extension oderwat.indent-rainbow
code --install-extension premparihar.gotestexplorer
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension robinbentley.sass-indented
code --install-extension slevesque.vscode-hexdump
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tomoki1207.pdf
code --install-extension uctakeoff.vscode-counter
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension Zignd.html-css-class-completion
