code --install-extensions aeschli.vscode-css-formatter
code --install-extensions anseki.vscode-color
code --install-extensions bierner.markdown-preview-github-styles
code --install-extensions CoenraadS.bracket-pair-colorizer
code --install-extensions CoenraadS.bracket-pair-colorizer-2
code --install-extensions donjayamanne.githistory
code --install-extensions dpastoor.vscode-nm
code --install-extensions eamodio.gitlens
code --install-extensions ecmel.vscode-html-css
code --install-extensions formulahendry.code-runner
code --install-extensions Gruntfuggly.todo-tree
code --install-extensions huizhou.githd
code --install-extensions kamikillerto.vscode-colorize
code --install-extensions letmaik.git-tree-compare
code --install-extensions mechatroner.rainbow-csv
code --install-extensions michelemelluso.code-beautifier
code --install-extensions ms-python.python
code --install-extensions ms-vscode.cpptools
code --install-extensions ms-vscode.Go
code --install-extensions msjsdiag.debugger-for-chrome
code --install-extensions naumovs.color-highlight
code --install-extensions nobuhito.printcode
code --install-extensions oderwat.indent-rainbow
code --install-extensions premparihar.gotestexplorer
code --install-extensions ritwickdey.live-sass
code --install-extensions ritwickdey.LiveServer
code --install-extensions robertohuertasm.vscode-icons
code --install-extensions robinbentley.sass-indented
code --install-extensions slevesque.vscode-hexdump
code --install-extensions streetsidesoftware.code-spell-checker
code --install-extensions tomoki1207.pdf
code --install-extensions trixnz.vscode-lua
code --install-extensions uctakeoff.vscode-counter
code --install-extensions waderyan.gitblame
code --install-extensions wayou.vscode-todo-highlight
code --install-extensions Zignd.html-css-class-completion
